//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vortex.GenerativeArtSuite.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vortex.GenerativeArtSuite.Create.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAS - Create.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URI:.
        /// </summary>
        public static string BaseURILabel {
            get {
                return ResourceManager.GetString("BaseURILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipfs://code.
        /// </summary>
        public static string BaseURIPlaceholder {
            get {
                return ResourceManager.GetString("BaseURIPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Size:.
        /// </summary>
        public static string CollectionSizeLabel {
            get {
                return ResourceManager.GetString("CollectionSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string CollectionSizePlaceholder {
            get {
                return ResourceManager.GetString("CollectionSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Layer.
        /// </summary>
        public static string CreateLayer {
            get {
                return ResourceManager.GetString("CreateLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        public static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layer.
        /// </summary>
        public static string DeleteLayer {
            get {
                return ResourceManager.GetString("DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the layer &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteLayerConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very gud nft :).
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layer.
        /// </summary>
        public static string EditLayer {
            get {
                return ResourceManager.GetString("EditLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in DNA:.
        /// </summary>
        public static string IsDNA {
            get {
                return ResourceManager.GetString("IsDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait doesn&apos;t make the token unique.
        /// </summary>
        public static string IsDNAOff {
            get {
                return ResourceManager.GetString("IsDNAOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait makes the token unique.
        /// </summary>
        public static string IsDNAOn {
            get {
                return ResourceManager.GetString("IsDNAOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Optional:.
        /// </summary>
        public static string IsOptional {
            get {
                return ResourceManager.GetString("IsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait always selected.
        /// </summary>
        public static string IsOptionalOff {
            get {
                return ResourceManager.GetString("IsOptionalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait may be &quot;none&quot;.
        /// </summary>
        public static string IsOptionalOn {
            get {
                return ResourceManager.GetString("IsOptionalOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Index:.
        /// </summary>
        public static string LayerIndex {
            get {
                return ResourceManager.GetString("LayerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified:.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Name Prefix:.
        /// </summary>
        public static string NamePrefixLabel {
            get {
                return ResourceManager.GetString("NamePrefixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Item.
        /// </summary>
        public static string NamePrefixPlaceholder {
            get {
                return ResourceManager.GetString("NamePrefixPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder:.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Account\Documents\Vortex\SessionNameOutput.
        /// </summary>
        public static string OutputFolderPlaceholder {
            get {
                return ResourceManager.GetString("OutputFolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Name:.
        /// </summary>
        public static string SessionNameLabel {
            get {
                return ResourceManager.GetString("SessionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SessionNamePlaceholder {
            get {
                return ResourceManager.GetString("SessionNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
