//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vortex.GenerativeArtSuite.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vortex.GenerativeArtSuite.Create.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Icon.
        /// </summary>
        public static string AddIcon {
            get {
                return ResourceManager.GetString("AddIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mask.
        /// </summary>
        public static string AddMask {
            get {
                return ResourceManager.GetString("AddMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trait.
        /// </summary>
        public static string AddTrait {
            get {
                return ResourceManager.GetString("AddTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAS - Create.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URI.
        /// </summary>
        public static string BaseURILabel {
            get {
                return ResourceManager.GetString("BaseURILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipfs://code.
        /// </summary>
        public static string BaseURIPlaceholder {
            get {
                return ResourceManager.GetString("BaseURIPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Builder.
        /// </summary>
        public static string CharacterBuilder {
            get {
                return ResourceManager.GetString("CharacterBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Session.
        /// </summary>
        public static string CloneSession {
            get {
                return ResourceManager.GetString("CloneSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Size.
        /// </summary>
        public static string CollectionSizeLabel {
            get {
                return ResourceManager.GetString("CollectionSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string CollectionSizePlaceholder {
            get {
                return ResourceManager.GetString("CollectionSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Layer.
        /// </summary>
        public static string CreateLayer {
            get {
                return ResourceManager.GetString("CreateLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        public static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trait.
        /// </summary>
        public static string CreateTrait {
            get {
                return ResourceManager.GetString("CreateTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layer.
        /// </summary>
        public static string DeleteLayer {
            get {
                return ResourceManager.GetString("DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the layer &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteLayerConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trait.
        /// </summary>
        public static string DeleteTrait {
            get {
                return ResourceManager.GetString("DeleteTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the trait &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteTraitConfirmation {
            get {
                return ResourceManager.GetString("DeleteTraitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very gud nft :).
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layer.
        /// </summary>
        public static string EditLayer {
            get {
                return ResourceManager.GetString("EditLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trait.
        /// </summary>
        public static string EditTrait {
            get {
                return ResourceManager.GetString("EditTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving.
        /// </summary>
        public static string ExitNoSave {
            get {
                return ResourceManager.GetString("ExitNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and exit.
        /// </summary>
        public static string ExitSave {
            get {
                return ResourceManager.GetString("ExitSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Url.
        /// </summary>
        public static string ExternalUrlLabel {
            get {
                return ResourceManager.GetString("ExternalUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://intothevortex.xyz/collection/{0} where {0} is the token id.
        /// </summary>
        public static string ExternalUrlPlaceholder {
            get {
                return ResourceManager.GetString("ExternalUrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation failed to complete, unique DNA threshold was broken, try to add more traits or reduce the collection size..
        /// </summary>
        public static string GenerationFailureNotEnoughTraits {
            get {
                return ResourceManager.GetString("GenerationFailureNotEnoughTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health check failed.
        /// </summary>
        public static string HealthCheckFailed {
            get {
                return ResourceManager.GetString("HealthCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Check Character Builder for more details..
        /// </summary>
        public static string HealthCheckFailedDetails {
            get {
                return ResourceManager.GetString("HealthCheckFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected by Layer Mask.
        /// </summary>
        public static string IsAffectedByMask {
            get {
                return ResourceManager.GetString("IsAffectedByMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignores layer mask.
        /// </summary>
        public static string IsAffectedByMaskOff {
            get {
                return ResourceManager.GetString("IsAffectedByMaskOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected by layer mask.
        /// </summary>
        public static string IsAffectedByMaskOn {
            get {
                return ResourceManager.GetString("IsAffectedByMaskOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string IsClone {
            get {
                return ResourceManager.GetString("IsClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string IsCloneOff {
            get {
                return ResourceManager.GetString("IsCloneOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string IsCloneOn {
            get {
                return ResourceManager.GetString("IsCloneOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in DNA.
        /// </summary>
        public static string IsDNA {
            get {
                return ResourceManager.GetString("IsDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait doesn&apos;t make the token unique.
        /// </summary>
        public static string IsDNAOff {
            get {
                return ResourceManager.GetString("IsDNAOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait makes the token unique.
        /// </summary>
        public static string IsDNAOn {
            get {
                return ResourceManager.GetString("IsDNAOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Traits.
        /// </summary>
        public static string IsDrawn {
            get {
                return ResourceManager.GetString("IsDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits are not drawn.
        /// </summary>
        public static string IsDrawnOff {
            get {
                return ResourceManager.GetString("IsDrawnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits are drawn.
        /// </summary>
        public static string IsDrawnOn {
            get {
                return ResourceManager.GetString("IsDrawnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Optional.
        /// </summary>
        public static string IsOptional {
            get {
                return ResourceManager.GetString("IsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait always selected.
        /// </summary>
        public static string IsOptionalOff {
            get {
                return ResourceManager.GetString("IsOptionalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait may be &quot;none&quot;.
        /// </summary>
        public static string IsOptionalOn {
            get {
                return ResourceManager.GetString("IsOptionalOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Index.
        /// </summary>
        public static string LayerIndex {
            get {
                return ResourceManager.GetString("LayerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate NFT retry amount.
        /// </summary>
        public static string MaxDuplicateDNAThresholdLabel {
            get {
                return ResourceManager.GetString("MaxDuplicateDNAThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string MaxDuplicateDNAThresholdPlaceholder {
            get {
                return ResourceManager.GetString("MaxDuplicateDNAThresholdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon image does not exist.
        /// </summary>
        public static string MissingIcon {
            get {
                return ResourceManager.GetString("MissingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask image does not exist.
        /// </summary>
        public static string MissingMask {
            get {
                return ResourceManager.GetString("MissingMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trait image does not exist.
        /// </summary>
        public static string MissingTrait {
            get {
                return ResourceManager.GetString("MissingTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Name Prefix.
        /// </summary>
        public static string NamePrefixLabel {
            get {
                return ResourceManager.GetString("NamePrefixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Item.
        /// </summary>
        public static string NamePrefixPlaceholder {
            get {
                return ResourceManager.GetString("NamePrefixPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        public static string NewSession {
            get {
                return ResourceManager.GetString("NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no layers. Return to the layers tab to add some..
        /// </summary>
        public static string NoLayers {
            get {
                return ResourceManager.GetString("NoLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Session.
        /// </summary>
        public static string OpenSession {
            get {
                return ResourceManager.GetString("OpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Account\Documents\Vortex\SessionNameOutput.
        /// </summary>
        public static string OutputFolderPlaceholder {
            get {
                return ResourceManager.GetString("OutputFolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Repository.
        /// </summary>
        public static string RemoteLabel {
            get {
                return ResourceManager.GetString("RemoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/user/project.git.
        /// </summary>
        public static string RemotePlaceholder {
            get {
                return ResourceManager.GetString("RemotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been changed, would you like to save your changes before going home?.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Session.
        /// </summary>
        public static string SaveSession {
            get {
                return ResourceManager.GetString("SaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Name.
        /// </summary>
        public static string SessionNameLabel {
            get {
                return ResourceManager.GetString("SessionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SessionNamePlaceholder {
            get {
                return ResourceManager.GetString("SessionNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
